'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Droplets, Waves, GlassWater, House, Leaf, MapPin, Mail, Phone, Check, Menu, X, SlidersHorizontal } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { business, reviews } from '@/lib/content';
const systems = [
 {name:'Whole-Home Water Filtration',icon:House,tag:'EVERY TAP. EVERY DAY.',text:'A filtration system at your main water line treats water before it reaches your showers, laundry, and kitchen.',detail:'A whole-home system can combine sediment and other filtration stages based on your water analysis. We help match treatment capacity to your household’s flow and usage.'},
 {name:'Water Softener Systems',icon:Waves,tag:'LESS SCALE. MORE COMFORT.',text:'Address the minerals behind hard-water spots, soap buildup, and scale on fixtures and appliances.',detail:'Softening reduces calcium and magnesium through ion exchange. Your hardness level and household water use guide system sizing and maintenance needs.'},
 {name:'Carbon Filtration Systems',icon:Leaf,tag:'A FRESHER EVERYDAY EXPERIENCE.',text:'Reduce chlorine taste and odor with carbon filtration selected for your home’s water supply.',detail:'Carbon media and contact time matter. Treatment for chloramine requires an appropriately designed system. '},
 {name:'Reverse Osmosis Drinking Water',icon:GlassWater,tag:'BETTER WATER, BY THE GLASS.',text:'Dedicated filtration for the water you drink, cook with, and pour into your morning coffee.',detail:'Typically installed at the kitchen sink, reverse osmosis uses a membrane and additional filter stages. Ask about the specific system’s certified reduction claims, replacement filters, and water efficiency.'},
 {name:'City Water Treatment',icon:SlidersHorizontal,tag:'MAKE YOUR CITY WATER YOURS.',text:'Build a treatment plan around your municipal supply, taste preferences, and household needs.',detail:'City water treatment may pair carbon filtration with softening or drinking-water filtration. '},
 {name:'Well Water Treatment Systems',icon:Droplets,tag:'START WITH YOUR SOURCE.',text:'Explore targeted treatment for sediment, staining, mineral buildup, and unpleasant odors.',detail:'Private wells treament may include sediment filtration, iron treatment, softening, or disinfection.'},
];
const faqs = [["How does whole-home filtration compare with reverse osmosis?", "A whole-home system treats water as it enters your house, serving showers, faucets, and appliances. Reverse osmosis typically treats water at a dedicated kitchen tap for drinking and cooking. Some homes use both."], ["Would a water softener help in my home?", "Recurring mineral deposits, spots on glassware, and soap buildup can point to hard water. A hardness test helps determine whether a softener would be useful and what size fits your household."], ["Do you offer solutions for municipal supplies and private wells?", "Yes. Frederick Pure Water offers treatment options for both. We consider your water source and testing results before recommending equipment for your home."], ["Which water concerns can carbon filtration address?", "An appropriately selected carbon filter can reduce chlorine-related taste and odor. Its ability to address other substances depends on the media, system design, and specific performance claims."], ["Where should I start when choosing a treatment system?", "Tell us about your water source, the issues you notice, and your household’s needs. We can discuss water testing, suitable treatment options, maintenance, and your budget during a free consultation."]];
function CTA({text='Get Free Consultation',className=''}:{text?:string,className?:string}) {return <a className={`button ${className}`} href="#consultation">{text}<ArrowUpRight size={18}/></a>}
function Brand(){return <a className="brand" href="#home" aria-label="Frederick Pure Water home"><Droplets size={36} strokeWidth={1.5}/><span>FREDERICK<strong>PURE WATER</strong></span></a>}
export default function Page(){
 const [menu,setMenu]=useState(false); const [source,setSource]=useState<string|null>('Not sure'); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setStatus('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch('/api/consultation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,source})});if(!response.ok) throw new Error();setSent(true);setStatus('Thank you. Your consultation request has been sent. We’ll contact you using the details you provided.');}catch{setStatus('Your request could not be sent. Please try again or email contact@frederickpurewater.com directly.');}finally{setBusy(false)}}
 return <><a className="skip" href="#main">Skip to content</a><div className="topbar"><span><MapPin size={13}/>Serving Howard, Montgomery & Frederick Counties</span><a href={`mailto:${business.email}`}>Email: {business.email}</a></div><header><div className="nav wrap"><Brand/><nav aria-label="Main navigation" className={menu?'open':''}>{[['Our systems','systems'],['How it works','process'],['Service areas','service-areas'],['Reviews','reviews']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="nav-actions">{business.phone?<a className="phone" href={`tel:+1${business.phone.replace(/[^\d]/g,'')}`}><Phone size={16}/>{business.phone}</a>:<a className="phone" href={`mailto:${business.email}`}><Mail size={16}/>Let’s talk water</a>}<CTA/><button className="menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main id="main"><section className="hero wrap" id="home"><div className="hero-copy"><p className="eyebrow"><span/>PURE WATER. RIGHT AT HOME.</p><h1>Better water.<br/>For every part<br/>of <em>your life.</em></h1><p className="intro">From your first glass to your evening shower. Whole-home water treatment, thoughtfully tailored to your Frederick home.</p><div className="hero-buttons"><CTA/><a className="text-link" href="#systems">Explore our systems <ArrowRight size={17}/></a></div><div className="hero-notes"><span><Check/>City & well water</span><span><Check/>Solutions for your home</span></div></div><div className="hero-visual"><img src="/images/kitchen-water.png" alt="A clear glass of water beside a faucet in a sunlit kitchen" width="1024" height="1024" fetchPriority="high"/><div className="photo-label"><Droplets/><div>Good water starts here.<span>Made for the way you live.</span></div></div><span className="vertical-caption">FREDERICK, MARYLAND</span></div></section>
 <div className="benefit-band"><div className="wrap"><span><GlassWater/>Better-tasting drinking water</span><span><Waves/>Less hard-water buildup</span><span><House/>Treatment throughout your home</span></div></div>
 <section className="section wrap" id="systems"><div className="section-head"><div><p className="eyebrow">YOUR WATER. YOUR SOLUTION.</p><h2>A better fit for<br/>every kind of water.</h2></div><p>City water or a private well. One concern or a few.<br/>Find a starting point below, we’ll help you<br className="desktop"/> bring the right solution home.</p></div><div className="systems-grid">{systems.map((s,i)=><article className="system" key={s.name}><div className="card-top"><s.icon size={30} strokeWidth={1.4}/><span>0{i+1}</span></div><p className="small-label">{s.tag}</p><h3>{s.name}</h3><p>{s.text}</p><details><summary>Explore this system <ArrowUpRight size={18}/></summary><p>{s.detail}</p><a href="#consultation">Ask about this system →</a></details></article>)}</div></section>
 <section className="process-section" id="process"><div className="wrap"><div className="section-head"><div><p className="eyebrow">A CLEAR PATH TO BETTER WATER</p><h2>Let’s take the guesswork<br/>out of your water.</h2></div><CTA/></div><div className="steps">{[['Tell us about your water','Share what you’re noticing, your water source, and what you’d like to improve.'],['Understand your options','Discuss treatment choices, your home’s needs, and a personalized system quote.'],['Bring better water home','Choose your system and coordinate installation, with a clear plan for ongoing care.']].map(([title,text],i)=><div key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
 <section className="section wrap about" id="about"><div className="about-mark"><Droplets size={66} strokeWidth={1}/><p>Your home.<br/>Your water.<br/><em>Our focus.</em></p><span>FREDERICK PURE WATER</span></div><div><p className="eyebrow">LOCAL HOMES. PERSONAL SOLUTIONS.</p><h2>Water treatment<br/>with your home in mind.</h2><p>Frederick Pure Water helps Frederick homeowners explore water treatment for everyday living from whole-home filtration and softening to drinking water systems.</p><p>Every home starts with a different water story. Your source, your household, and your priorities guide the conversation, so you can make an informed decision about what comes next.</p><a className="text-link" href="#consultation">Let’s talk about your water <ArrowRight size={18}/></a></div></section>
 <section className="service-areas-section" id="service-areas"><div className="wrap"><p className="eyebrow">LOCAL WATER TREATMENT</p><div className="section-head"><h2>Better water.<br/>Across our Maryland communities.</h2><p>Frederick Pure Water serves homeowners in Howard County, Montgomery County, and Frederick County. Let’s find the right treatment for your home.</p></div><ul className="county-list">{['Howard County','Montgomery County','Frederick County'].map(county=><li key={county}><MapPin size={25}/><span>{county}<small>Maryland</small></span></li>)}</ul><CTA/></div></section>
 <section className="reviews-section" id="reviews"><div className="wrap"><div className="section-head"><div><p className="eyebrow">CUSTOMER REVIEW LAYOUT · PREVIEW</p><h2>The difference<br/>better water makes.</h2></div><p>{'Homeowners choose Frederick Pure Water for honest recommendations, professional service, and noticeable improvements in their water quality'}</p></div><div className="review-track">{reviews.map((r,i)=><article className="review" key={i}>{r.approved?<>{r.rating > 0 && <p className="review-stars" aria-label={`${r.rating} out of 5 stars`}>{'★'.repeat(r.rating)}</p>}<div className="review-person"><span className="review-avatar">{r.name.slice(0,1).toUpperCase()}{r.image && <img src={r.image} alt={`${r.name} profile photo from the reference site`} width="48" height="48" loading="lazy" referrerPolicy="no-referrer" onError={event=>{event.currentTarget.style.display='none'}}/>}</span><div><strong>{r.name}</strong></div></div><p className="review-summary">{r.text}</p></>:<><span className="review-slot">CUSTOMER STORY {String(i+1).padStart(2,'0')}</span><p className="quote-mark">“</p><h3>A homeowner’s perspective.</h3><p>Awaiting an approved customer review.</p></>}</article>)}</div><p className="review-caption"></p></div></section>
 <section className="section wrap faq"><div><p className="eyebrow">A LITTLE MORE CLARITY</p><h2>Good questions.<br/>Clear answers.</h2><p>Still have something on your mind?</p><a className="text-link" href={`mailto:${business.email}`}>Email our team <ArrowUpRight size={18}/></a></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="consultation-section" id="consultation"><div className="wrap consultation"><div><p className="eyebrow">BETTER WATER BEGINS WITH A CONVERSATION</p><h2>Let’s find the right<br/>water solution<br/>for <em>your home.</em></h2><p>Tell us a little about your home. Request a free consultation and a personalized quote from Frederick Pure Water.</p><div className="contact-lines">{business.phone&&<a href={`tel:+1${business.phone.replace(/[^\d]/g,'')}`}><Phone/>{business.phone}</a>}<a href={`mailto:${business.email}`}><Mail/>{business.email}</a><span><MapPin/>Serving Howard, Montgomery & Frederick Counties, Maryland</span></div></div><form onSubmit={submit}><p className="eyebrow">YOUR NEXT STEP</p><h3>Get your free consultation.</h3><p>Let’s start with a few details.</p><div className="form-grid"><label>Full name<input name="name" autoComplete="name" required maxLength={120} placeholder="Your name"/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required minLength={7} maxLength={30} placeholder="(301) 555-0123"/></label><label className="full">Email address<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label><label className="full">Home address<input name="address" autoComplete="street-address" required maxLength={250} placeholder="Street address, city, ZIP"/></label><div className="full field"><label id="source-label">Your water source</label><Select value={source} onValueChange={setSource}><SelectTrigger aria-labelledby="source-label" className="source-select"><SelectValue/></SelectTrigger><SelectContent>{['Not sure','City water','Private well'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><label className="full">What would you like to improve? <span>(optional)</span><textarea name="message" rows={3} maxLength={2000} placeholder="Hard water, taste, odors, or a system you’re interested in…"/></label></div><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><button className="button" disabled={busy||sent} type="submit">{busy?'Sending…':sent?'Request sent':'Get Free Consultation'}<ArrowUpRight size={18}/></button><p className="form-fine">By submitting, you ask us to contact you about this request. <a href="#privacy">How we use your information</a>.</p><p role="status" className={status?'form-status':''}>{status}</p></form></div></section>
 </main><footer><div className="wrap"><div className="footer-top"><div><Brand/><p>Better water. Right at home.</p></div><div><h3>Explore</h3><a href="#systems">Our systems</a><a href="#process">How it works</a><a href="#service-areas">Service areas</a><a href="#about">About us</a><a href="#reviews">Customer reviews</a></div><div><h3>Get in touch</h3><a href={`mailto:${business.email}`}>Email: {business.email}</a>{business.phone&&<a href={`tel:+1${business.phone.replace(/[^\d]/g,'')}`}>{business.phone}</a>}<a href="#consultation">Get Free Consultation ↗</a></div></div><details id="privacy" className="privacy"><summary>Privacy & your consultation request</summary><p>Frederick Pure Water uses the contact details, address, and water concerns you submit to respond to your inquiry and prepare service recommendations. Requests are delivered through our email provider. Please do not submit sensitive information. To ask about your information or request deletion, email {business.email}.</p></details><div className="footer-bottom"><span>© {new Date().getFullYear()} Frederick Pure Water.</span><span>Serving Howard, Montgomery & Frederick Counties.</span></div></div></footer><div className="mobile-cta"><a className="mobile-phone" href="tel:+12023562779"><Phone size={18}/><span>Call us<strong>{business.phone}</strong></span></a><CTA/></div></>;
}
